# Generated by Django 5.2.6 on 2025-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
