# Generated by Django 5.2.6 on 2025-10-27 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('services', '0002_remove_governmentservice_rate_limit_per_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, help_text='Email subject', max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification')], max_length=10)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], default='PENDING', max_length=20)),
                ('webhook_url', models.URLField(blank=True, help_text='Callback URL for status updates', null=True)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('webhook_sent_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_response', models.JSONField(blank=True, help_text='Response from webhook call', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional request metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_requests', to='services.governmentservice')),
            ],
            options={
                'db_table': 'notification_requests',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='notification_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='notifications.notificationrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationrequest'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_request', 'status'], name='notificatio_notific_4a0e05_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_2ea0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_address'], name='notificatio_recipie_0fa345_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrequest',
            index=models.Index(fields=['service', 'created_at'], name='notificatio_service_b00901_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrequest',
            index=models.Index(fields=['status'], name='notificatio_status_1e5703_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrequest',
            index=models.Index(fields=['created_at'], name='notificatio_created_7878a4_idx'),
        ),
    ]
