# Generated by Django 5.2.6 on 2025-11-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_recipient_name_notification_retry_count_and_more'),
        ('services', '0002_remove_governmentservice_rate_limit_per_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.governmentservice'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.governmentservice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.governmentservice'),
        ),
    ]
