# Generated by Django 5.2.6 on 2025-11-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_batch_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.notificationtemplate'),
        ),
    ]
