# Generated by Django 5.2.6 on 2025-11-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_variables_to_template'),
        ('notifications', '0004_alter_notification_notification_template'),
    ]

    operations = [
    ]
