# Generated by Django 5.2.6 on 2025-12-01 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_merge_20251120_0931'),
        ('services', '0002_remove_governmentservice_rate_limit_per_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.governmentservice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.governmentservice'),
        ),
        migrations.AlterField(
            model_name='notificationrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_requests', to='services.governmentservice'),
        ),
    ]
