# Generated by Django 5.2.6 on 2025-10-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentservice',
            name='rate_limit_per_minute',
        ),
    ]
