# Generated by Django 5.2.6 on 2025-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_governmentservice_rate_limit_per_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentservice',
            name='allowed_batch_size',
            field=models.IntegerField(default=10000),
        ),
    ]
