# Generated by Django 5.2.6 on 2025-12-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_governmentservice_allowed_batch_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentservice',
            options={'ordering': ['created_at']},
        ),
    ]
